name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Print Current Directory
      run: pwd

    - name: Print Chromedriver Directory
      run: ls -l src/test/resources/com/stacks/bdd/selenium/driver/

    - name: Debug Chromedriver Path
      run: echo "Current Directory: $(pwd), File Exists: $(test -e src/test/resources/com/stacks/bdd/selenium/driver/chromedriver && echo true || echo false)"

    - name: Set Chromedriver permissions
      run: chmod +x src/test/resources/com/stacks/bdd/selenium/driver/chromedriver

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Selenium Tests with Chrome
      run: mvn test -P selenium-chrome
