name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clean_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clean Build
      run: |
        mvn clean
        rm -rf target

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set WebDriverManager Log Level
      run: |
        mvn io.github.bonigarcia:wdm-maven-plugin:latest-version:properties -DdownloadRoot=http://repo1.maven.org/maven2 -DoutputFile=wdm.properties
        cat wdm.properties

  your_other_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clean Build
      run: |
        mvn clean
        rm -rf target

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set WebDriverManager Log Level
      run: |
        mvn io.github.bonigarcia:wdm-maven-plugin:latest-version:properties -DdownloadRoot=http://repo1.maven.org/maven2 -DoutputFile=wdm.properties
        cat wdm.properties

  your_third_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clean Build
      run: |
        mvn clean
        rm -rf target

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set WebDriverManager Log Level
      run: |
        mvn io.github.bonigarcia:wdm-maven-plugin:latest-version:properties -DdownloadRoot=http://repo1.maven.org/maven2 -DoutputFile=wdm.properties
        cat wdm.properties
