name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Download ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -qP src/test/resources/com/stacks/bdd/selenium/driver/ "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip -q -d src/test/resources/com/stacks/bdd/selenium/driver/ "src/test/resources/com/stacks/bdd/selenium/driver/chromedriver_linux64.zip"
        rm src/test/resources/com/stacks/bdd/selenium/driver/chromedriver_linux64.zip
